model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: models/${now:%H-%M-%S}/ # directory to save the model file
  filename: ${model.model_name_or_path}_{epoch}-{val_acc:.2f}
  monitor: "val_acc" # name of the logged metric which determines when model is improving
  verbose: False # verbosity mode
  save_top_k: 3 # save k best models (determined by above metric)
  mode: "max" # "max" means higher metric value is better, can be also "min"
  auto_insert_metric_name: True # when True, the checkpoints filenames will contain the metric name
  save_weights_only: False # if True, then only the modelâ€™s weights will be saved
  every_n_epochs: 3 # number of epochs between checkpoints
  save_on_train_epoch_end: False # whether to run checkpointing at the end of the training epoch or the end of validation